# local-config.yaml
# 是否开启认证
auth_enabled: false
# HTTP和gRPC服务监听地址
server:
  http_listen_port: 3100
  grpc_listen_port: 9095
# 配置日志索引和存储
schema_config:
  configs:
    - from: 2018-04-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# 配置日志存储后端
storage_config:
  boltdb:
    directory: /data/loki/index
  filesystem:
    directory: /data/loki/chunks

# 配置日志收集
ingester:
  wal:
    enabled: true
    dir: "/tmp/wal"
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
      heartbeat_timeout: 1m
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s