# promtail config yml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki-svc:3100/loki/api/v1/push

scrape_configs:
- job_name: log
  static_configs:
  - targets:
      - localhost
    labels:
      job: audit
      __path__: /log/*log