# docker-compose.yml
version: '3.7'
networks:
  loki-net:
    driver: bridge
services:
  loki:
    networks:
      loki-net:
        aliases:
         - loki-svc
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./config:/etc/loki
      - ./data:/data/loki

  promtail:
    networks:
      loki-net:
        aliases:
         - promtail-svc
    image: grafana/promtail:latest
    privileged: true
    volumes:
      - ./config:/config
      - ./log:/log
    command: -config.file=/config/promtail-config.yaml