apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
  namespace: dev
  # 标签选择器-在service之中一定需要
  labels:
    environment: production
    app: nginx
spec:
  containers:
    - name: nginx-containers
      image: nginx:1.17.1