apiVersion: v1 # 版本
kind: Service # 类型
metadata: # 元数据
  name: nginxservice # 资源名称
  namespace: dev # 命名空间
spec:
  selector: # 标签选择器，用于确定当前Service代理那些Pod
    app: nginx
  type: NodePort # Service的类型，指定Service的访问方式
  clusterIP: # 虚拟服务的IP地址
  sessionAffinity: # session亲和性，支持ClientIP、None两个选项，默认值为None
  ports: # 端口信息
    - port: 8080 # Service端口
      protocol: TCP # 协议
      targetPort : 80 # Pod端口
      nodePort: 30681 # 主机端口